### ISSUE TITLE
Custom events cannot be saved

### ISSUE THREAD

**Issue by xyaayx** [Battlehub0x/RTE_Docs#102]
Custom events that correctly display and reference other script functions in the Inspector panel, but lost the reference after reopening the scene.  The OnClick of the Button can be accessed normally.thanks.
![20231225175445](https://github.com/Battlehub0x/RTE_Docs/assets/37795033/9b80a0b2-44b4-41ec-8276-522196dbf9c4)

**Comment by Battlehub0x** [comment]
![thumbnail_1703562418015](https://github.com/Battlehub0x/RTE_Docs/assets/15802443/7ea4c152-66b1-47dc-99be-f38d2a84c3aa)

I think the problem is that Runtime Editor doesn't support serialization events with generic parameters.

In your example I see 2 of them: Before<T> and Before<T0, T1>. 

I know this can potentially result in multiple redundant classes, but if you have access to the code that creates these events, you can workaround the problem by creating and using non-generic versions of these events.
